version: "3.9"

services:
  backend:
    image: mx-app-backend
    restart: always
    env_file: backend/.env.prod
    build: backend
    command: gunicorn --worker-class gevent --workers 2 --bind 0.0.0.0:3000 wsgi:app --log-level debug

  
  frontend:
    image: mx-app-frontend
    restart: always
    build: frontend


  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend